name: Unit Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        cd ./responder_app
        python -m pip install --upgrade pip
        pip install pipenv --upgrade-strategy=only-if-needed
        sed -ri 's/python_version = ".+"/python_version = "${{ matrix.python }}"/g' Pipfile
        pipenv install --dev --skip-lock
    - run: |
        cd ./responder_app
        pipenv run test